param(
    [string]$EnvFile = "",
    [switch]$AllowMissingSubscribeTemplate
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
if (-not $EnvFile) {
    $EnvFile = Join-Path $projectRoot "miniprogram\.env"
}
$EnvFile = [System.IO.Path]::GetFullPath($EnvFile)

if (-not (Test-Path -LiteralPath $EnvFile -PathType Leaf)) {
    throw "Config file not found: $EnvFile. Copy miniprogram/.env.example to miniprogram/.env and fill it in."
}

$values = @{}
foreach ($line in Get-Content -Encoding UTF8 -LiteralPath $EnvFile) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) { continue }
    $parts = $trimmed -split "=", 2
    if ($parts.Count -eq 2) {
        $values[$parts[0].Trim()] = $parts[1].Trim()
    }
}

foreach ($key in @("USE_CLOUD", "CLOUD_ENV_ID", "CLOUD_SERVICE_NAME")) {
    if (-not $values[$key] -or $values[$key] -match "^your_") {
        throw "Missing valid config: $key"
    }
}

$useCloud = $values["USE_CLOUD"].ToLowerInvariant()
if ($useCloud -notin @("true", "false")) {
    throw "USE_CLOUD must be true or false"
}
if ($useCloud -ne "true") {
    throw "Production config requires USE_CLOUD=true"
}

$templateId = $values["SUBSCRIBE_TEMPLATE_ID"]
if ((-not $templateId -or $templateId -match "^your_") -and -not $AllowMissingSubscribeTemplate) {
    throw "Missing valid SUBSCRIBE_TEMPLATE_ID. Use -AllowMissingSubscribeTemplate only when intentionally disabling subscribe messages."
}
if (-not $templateId -or $templateId -match "^your_") { $templateId = "" }

function ConvertTo-JsString([string]$value) {
    if ($null -eq $value) { $value = "" }
    return ($value | ConvertTo-Json -Compress)
}

$outputPath = Join-Path $projectRoot "miniprogram\utils\config.generated.js"
$content = @"
// Generated by scripts/generate-miniprogram-config.ps1. Do not commit.
module.exports = {
  SUBSCRIBE_TEMPLATE_ID: $(ConvertTo-JsString $templateId),
  USE_CLOUD: true,
  CLOUD_ENV_ID: $(ConvertTo-JsString $values["CLOUD_ENV_ID"]),
  CLOUD_SERVICE_NAME: $(ConvertTo-JsString $values["CLOUD_SERVICE_NAME"]),
  DIRECT_API_BASE: $(ConvertTo-JsString $values["DIRECT_API_BASE"]),
}
"@

[System.IO.File]::WriteAllText($outputPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated: $outputPath"
